services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: luxiva_ecommerce
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql.b64:/docker-entrypoint-initdb.d/init.sql.b64
      - ./mysql/decode_and_copy.sh:/docker-entrypoint.sh
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  fastapi_app:
    build: ./backend                        # <--- updated from ./app to ./backend
    image: backend_fastapi_shree:1.0          
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    env_file:
      - ./backend/.env
