version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./db/encrypted.sql:/encrypted.sql                # mounted directly
      - db_init:/docker-entrypoint-initdb.d              # shared with DB container

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newecommerce
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - db_init:/docker-entrypoint-initdb.d              # same shared volume

volumes:
  db_data:
  db_init:
